server:
  port: 8090
spring:
  profile: default
  application:
    name: credito
  datasource:
    password: senha
    url: jdbc:postgresql://localhost:5432/creditos
    username: usuario
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true